apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-volume-3231
  labels:
    pv: pv-nfs
spec:
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteMany
  nfs:
    path: /file-storage
    server: 192.168.56.20